### ISSUE TITLE
Feature: User details and avatar component

### ISSUE THREAD

**Issue by jakezachariahnixon** [jakezachariahnixon/todo-app#4]
- UserDetails component in the sidebar
- Avatar component nested within UserDetails
- No functionality required yet, can be set up with preset data and with blank avatar

**Comment by HaoHuynh0301** [comment]
Hi! Can you assign this for me ? I thing I can solve this issue. @jakezachariahnixon

**Comment by jakezachariahnixon** [comment]
Thank you for your contribution 🎉
